// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CLA.Data
{
    public partial class Banner
    {
        public string Id { get; set; }
        public string BannerName { get; set; }
        public string ImageUrl { get; set; }
        public short? Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}