// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CLA.Data
{
    public partial class Posts
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Thumbnail { get; set; }
        public string ShortDescription { get; set; }
        public string Content { get; set; }
        public short Status { get; set; }
        public int DisplayOrder { get; set; }
        public string AuthorId { get; set; }
        public DateTime PublishDate { get; set; }
        public string Tags { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}